# Generated by Django 3.0.7 on 2022-10-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='branch',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='city',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='district',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='state',
            field=models.CharField(max_length=25),
        ),
    ]
